// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoutePlanner.API.Data;

#nullable disable

namespace RoutePlanner.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221131904_AddGeometryToRouteLeg")]
    partial class AddGeometryToRouteLeg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoutePlanner.API.Models.Campsite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activities")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descriptions")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImagePaths")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("NumberOfSpots")
                        .HasColumnType("integer");

                    b.Property<string>("Park4NightId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Price")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric");

                    b.Property<string>("Services")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Types")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Name");

                    b.HasIndex("Park4NightId")
                        .IsUnique();

                    b.HasIndex("Rating");

                    b.HasIndex("SourceUrl")
                        .IsUnique();

                    b.ToTable("Campsites");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Beautiful beaches and coastal areas",
                            Icon = "🏖️",
                            Name = "Beach"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mountain ranges and hiking areas",
                            Icon = "🏔️",
                            Name = "Mountain"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Restaurants and dining locations",
                            Icon = "🍴",
                            Name = "Restaurant"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Museums and cultural sites",
                            Icon = "🏛️",
                            Name = "Museum"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Parks and natural areas",
                            Icon = "🌳",
                            Name = "Park"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Shopping centers and markets",
                            Icon = "🛍️",
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Adventure and outdoor activities",
                            Icon = "🎢",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Historic sites and landmarks",
                            Icon = "🏰",
                            Name = "Historic"
                        });
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NZ",
                            Description = "Island country in the southwestern Pacific Ocean",
                            Icon = "🇳🇿",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AU",
                            Description = "Country and continent in Oceania",
                            Icon = "🇦🇺",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 3,
                            Code = "US",
                            Description = "Federal republic in North America",
                            Icon = "🇺🇸",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DE",
                            Description = "Federal republic in Central Europe",
                            Icon = "🇩🇪",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 5,
                            Code = "FR",
                            Description = "Republic in Western Europe",
                            Icon = "🇫🇷",
                            Name = "France"
                        },
                        new
                        {
                            Id = 6,
                            Code = "IT",
                            Description = "Republic in Southern Europe",
                            Icon = "🇮🇹",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            Code = "ES",
                            Description = "Kingdom in Southwestern Europe",
                            Icon = "🇪🇸",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 8,
                            Code = "GB",
                            Description = "Island nation in Northwestern Europe",
                            Icon = "🇬🇧",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 9,
                            Code = "CA",
                            Description = "Country in North America",
                            Icon = "🇨🇦",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 10,
                            Code = "JP",
                            Description = "Island nation in East Asia",
                            Icon = "🇯🇵",
                            Name = "Japan"
                        });
                });

            modelBuilder.Entity("RoutePlanner.API.Models.GoogleMapsCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<string>("ApiType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("HitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SearchQuery")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Types")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("GooglePlaceId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Name");

                    b.HasIndex("SearchQuery");

                    b.ToTable("GoogleMapsCache");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.GooglePlaceData", b =>
                {
                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BusinessStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PriceLevel")
                        .HasColumnType("integer");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("SyncVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Types")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserRatingsTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("GooglePlaceId");

                    b.HasIndex("LastSyncedAt");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Name");

                    b.ToTable("GooglePlaceData");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GooglePlaceId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "GooglePlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (172.6362 -43.5321)"),
                            Name = "Christchurch",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (174.7762 -41.2865)"),
                            Name = "Wellington",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (174.7633 -36.8485)"),
                            Name = "Auckland",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RoutePlanner.API.Models.PlaceCategory", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("PlaceId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceCategories");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.PlaceCountry", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.HasKey("PlaceId", "CountryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceCountries");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.PlacePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("google");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GooglePlaceId");

                    b.HasIndex("GooglePlaceId", "IsPrimary")
                        .HasFilter("\"IsPrimary\" = true");

                    b.ToTable("PlacePhotos");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("DefaultArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("DefaultDepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("StartDateTime")
                        .HasColumnType("timestamptz");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The best of New Zealand",
                            Name = "New Zealand Highlights",
                            TimeZoneId = "Europe/Berlin",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("RoutePlanner.API.Models.RouteLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("FromRoutePlaceId")
                        .HasColumnType("integer");

                    b.Property<LineString>("Geometry")
                        .HasColumnType("geometry (linestring, 4326)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("ToRoutePlaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromRoutePlaceId");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("ToRoutePlaceId");

                    b.HasIndex("RouteId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("RouteLegs");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.RoutePlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEndLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStartLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PlannedEnd")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("PlannedStart")
                        .HasColumnType("timestamptz");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int?>("StayDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("StayNights")
                        .HasColumnType("integer");

                    b.Property<int>("StopType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("PlannedEnd");

                    b.HasIndex("PlannedStart");

                    b.HasIndex("RouteId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("RoutePlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEndLocked = false,
                            IsStartLocked = false,
                            OrderIndex = 0,
                            PlaceId = 1,
                            RouteId = 1,
                            StopType = 0
                        },
                        new
                        {
                            Id = 2,
                            IsEndLocked = false,
                            IsStartLocked = false,
                            OrderIndex = 1,
                            PlaceId = 2,
                            RouteId = 1,
                            StopType = 0
                        },
                        new
                        {
                            Id = 3,
                            IsEndLocked = false,
                            IsStartLocked = false,
                            OrderIndex = 2,
                            PlaceId = 3,
                            RouteId = 1,
                            StopType = 0
                        });
                });

            modelBuilder.Entity("RoutePlanner.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "default@roadtrip.local",
                            PasswordHash = "placeholder",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "default"
                        });
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Place", b =>
                {
                    b.HasOne("RoutePlanner.API.Models.GooglePlaceData", "GoogleData")
                        .WithMany("Places")
                        .HasForeignKey("GooglePlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RoutePlanner.API.Models.User", "User")
                        .WithMany("Places")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoogleData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.PlaceCategory", b =>
                {
                    b.HasOne("RoutePlanner.API.Models.Category", "Category")
                        .WithMany("PlaceCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutePlanner.API.Models.Place", "Place")
                        .WithMany("PlaceCategories")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.PlaceCountry", b =>
                {
                    b.HasOne("RoutePlanner.API.Models.Country", "Country")
                        .WithMany("PlaceCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutePlanner.API.Models.Place", "Place")
                        .WithMany("PlaceCountries")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.PlacePhoto", b =>
                {
                    b.HasOne("RoutePlanner.API.Models.GooglePlaceData", "GooglePlace")
                        .WithMany("Photos")
                        .HasForeignKey("GooglePlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GooglePlace");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Route", b =>
                {
                    b.HasOne("RoutePlanner.API.Models.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.RouteLeg", b =>
                {
                    b.HasOne("RoutePlanner.API.Models.RoutePlace", "FromRoutePlace")
                        .WithMany()
                        .HasForeignKey("FromRoutePlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoutePlanner.API.Models.Route", "Route")
                        .WithMany("Legs")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoutePlanner.API.Models.RoutePlace", "ToRoutePlace")
                        .WithMany()
                        .HasForeignKey("ToRoutePlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRoutePlace");

                    b.Navigation("Route");

                    b.Navigation("ToRoutePlace");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.RoutePlace", b =>
                {
                    b.HasOne("RoutePlanner.API.Models.Place", "Place")
                        .WithMany("RoutePlaces")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoutePlanner.API.Models.Route", "Route")
                        .WithMany("Places")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Category", b =>
                {
                    b.Navigation("PlaceCategories");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Country", b =>
                {
                    b.Navigation("PlaceCountries");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.GooglePlaceData", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Place", b =>
                {
                    b.Navigation("PlaceCategories");

                    b.Navigation("PlaceCountries");

                    b.Navigation("RoutePlaces");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.Route", b =>
                {
                    b.Navigation("Legs");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("RoutePlanner.API.Models.User", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
